version: "2"
services:
  npm:
    image: mkenney/npm
    volumes:
      - './web:/src'
  web:
    image: nginx:latest
    volumes:
      - './web/build:/app'
      - './docker/nginx/site.conf:/etc/nginx/conf.d/site.conf'
